### PR TITLE
Add a recommendation to follow the format from Keep a Changelog

### PR DESCRIPTION
**Pull request by Revisor**

### CODE REVIEW

**Comment by pmjones** [comment]
(/me nods along with @Revisor)

Yeah, I get this.

Even so, I am wary of making recommendations, however sensible, that are not backed by the research in some fashion. E.g., licensing, which seems an obvious no-brainer, is not strictly supported by the analysis. (See #1, which ends up adding a SHOULD for a license file.)

**Comment by Revisor** [comment]
PDS could recommend a few best practices (semver, structured changelog), what do you think?

For semver, there is an argument in form of Composer, which is built around it.
For a changelog format, I don't know. It's just sensible in itself. :)

**Comment by pmjones** [comment]
For the changelog stuff, there is a way forward that can be supported by research, but it would require some effort. You would need to identify the packages using a changelog, go to their repos, examine the file in question, determine if it matches a particular format, then tally the package/format counts. That would give some support to a recommendation.

**Comment by pmjones** [comment]
Closing this as "not supported by the existing research."

However, due to the versioned nature of the publications, further research might reveal that Keep A Changelog is the most common format, in which case a minor version with a "MAY" or "SHOULD" can be added.

Regardless, thanks for the suggestion.

**Pull request closed without merging**
