### PR TITLE
Exit with an evaluable return code

### PR DESCRIPTION
**Pull request by raphaelstolt**
Validate command can now be evaluated.

### CODE REVIEW

**Comment by pmjones** [comment]
You're right; there should be an evaluable exit. But the place to put it is not in the `execute()` method; instead, it should be in the `bin/pds-skeleton` script. If you can, modify this PR (or submit a new PR) so that `bin/pds-skeleton` takes the return from the `execute()` method, and then uses that for an exit code. Make sense?

**Comment by raphaelstolt** [comment]
Done via 7e1a096bc6fb399ccd8ad9961ef62816c5b3b163.

**Comment by pmjones** [comment]
@raphaelstolt right on!

@afilina -- please review, if you have the time and inclination.

**Comment by afilina** [comment]
Read code: ✓
Executed tests: ✓
Executed code: ✓

**Pull request merged**
