### PR TITLE
Add a recommendation to follow semantic versioning

### PR DESCRIPTION
**Pull request by Revisor**

### CODE REVIEW

**Comment by pmjones** [comment]
Hi @Revisor -- While I am a fan of SemVer, and would like to see more people follow it (especially in spirit), I wonder if such a recommendation is within the scope of a "package skeleton" recommendation.

**Comment by pmjones** [comment]
@Revisor -- any further thoughts on this? I am leaning toward closing it as "out of scope".

Also, thanks for your attention here, and for your comments on Reddit. :-)

**Comment by Revisor** [comment]
I don't know what you have in mind for php-pds.

If this is the only project in php-pds, I would add it here. If you plan another set of rules and recommendations, I would add it there. But I think this, and the changelog format, are good practices and could be RECOMMENDED.

I'll leave it up to you.

Thanks for thinking about these things.

**Comment by pmjones** [comment]
Hey @Revisor -- thanks for your collegial approach. I'm going to close this as "out of scope", but:

>If you plan another set of rules and recommendations

I expect there to be other publications, and if/when one of them relates to SemVer, I'll include it there as appropriate.

Thanks again!

**Pull request closed without merging**
