### PR TITLE
Generator

### PR DESCRIPTION
**Pull request by afilina**
Refactored validator and added package generator cli tool. #23

### CODE REVIEW

**Comment by pmjones** [comment]
A couple of things stand out to me:

1. Let's use `Pds\` instead of `PDS\`.

2. Under PSR-4, the directories can be collapsed for the namespace prefix, so the source code can be directly in the `src/` directory, and don't need to be in `src/Pds/Skeleton/`.  Can you move those files, and update the composer.json in line with that (`"psr-4": { "PDS\\Skeleton\\": "src/" }`) ?

**Comment by afilina** [comment]
@pmjones I made the changes.

**Comment by pmjones** [comment]
I see some minor issues but no blockers. Thanks!

**Comment by afilina** [comment]
Let me know how I can improve it.

**Pull request merged**
